name: Build & Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            build_flag: --linux
            publish: --publish always
          - os: windows-2022
            build_flag: --win
            publish: --publish never
          - os: macos-14
            build_flag: --mac
            publish: --publish never
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npx electron-builder ${{ matrix.build_flag }} ${{ matrix.publish }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
